### ISSUE TITLE
CREATE EXTENSION dbms_sql is giving error

### ISSUE THREAD

**Issue by naveenjul29** [okbob/dbms_sql#1]
I am getting the below error while running the command **CREATE EXTENSION IF NOT EXISTS dbms_sql**; 

ERROR:  type "varchar2" already exists
SQL state: 42710

**Note**: I followed the steps in installation document.

**Comment by okbob** [comment]
po 31. 8. 2020 v 7:02 odesílatel naveenjul29 <notifications@github.com>
napsal:

> I am getting the below error while running the command *CREATE EXTENSION
> IF NOT EXISTS dbms_sql*;
>
> ERROR: type "varchar2" already exists
> SQL state: 42710
>
> *Note*: I followed the steps in installation document.
>
There can be collision with Orafce varchar2

look to dbms_sql--1.0.sql
/* dbms_sql.sql */

-- complain if script is sourced in psql, rather than via CREATE EXTENSION
\echo Use "CREATE EXTENSION dbms_sql" to load this file. \quit
CREATE SCHEMA dbms_sql;

/*
 * temp solution, at the end varchar2 from orafce will be used
 */
CREATE DOMAIN varchar2 AS text; -- should be removed, if you use Orafce

and similar line in doc

## Dependency

When you plan to use dbms_sql extension together with Orafce, then you have
to remove line
with `CREATE DOMAIN varchar2 AS text;` statement from install sql script.

or maybe you have own varchar2 type

**Comment by naveenjul29** [comment]
I got it. Thank you :)
