### ISSUE TITLE
ERROR:  type "varchar2" already exists

### ISSUE THREAD

**Issue by darold** [okbob/dbms_sql#2]
Hi Pavel,

This morning I tried to install the dbms_sql extension and I'm facing the well know error in $subject. It is documented in the extension SQL file:
```
/*
 * temp solution, at the end varchar2 from orafce will be used
 */
CREATE DOMAIN varchar2 AS text; -- should be removed, if you use Orafce
```

My question is what is the interest in keeping the `varchar2` data type in this extension instead of using varchar or text? I mean if the user use the varchar2 data type it must  probably already  have the orafce extension installed and in the orafce extension there is implicit cast to varchar and varchar2. 

Best regards

**Comment by okbob** [comment]
Hi

so 5. 2. 2022 v 7:58 odesílatel Gilles Darold ***@***.***>
napsal:

> Hi Pavel,
>
> This morning I tried to install the dbms_sql extension and I'm facing the
> well know error in $subject. It is documented in the extension SQL file:
>
> /*
>  * temp solution, at the end varchar2 from orafce will be used
>  */
> CREATE DOMAIN varchar2 AS text; -- should be removed, if you use Orafce
>
> My question is what is the interest in keeping the varchar2 data type in
> this extension instead of using varchar or text? I mean if the user use the
> varchar2 data type it must probably already have the orafce extension
> installed and in the orafce extension there is implicit cast to varchar and
> varchar2.
>
Because dbms_sql uses procedures, it cannot be merged with Orafce now. I am
waiting on ending 9.6 support (and maybe pg 10 next year). Then I'll
integrate it with Orafce.

Using domain is just a temporary solution to allow testing without Orafce.
But maybe I can reverse direction, and enforce dependency on Orafce. It is
true, so probably nobody will use dbms_sql without Orafce.

Regards

Pavel

**Comment by darold** [comment]
Ok thank you Pavel, I was sure that there was a good reason I was just curious to know it :-) Thanks again.
